<a href="https://colab.research.google.com/github/146790g/Python-File-Manipulation/blob/master/FM_No_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# keras.preprocessing.image による画像データのハンドリング

## 複数の画像データを読み込んで、4階テンソルの配列データに変換する



In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


### 1枚のカラー画像データの読み込んで、3階テンソルの配列データに変換する

In [16]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import load_img, img_to_array
import os

%pwd

root_dir = '/content/gdrive/My Drive/Colab Notebooks/Python File Manipulation'

file=os.path.join(root_dir,'ice.jpg')

img = load_img(file,target_size=(200,200))

print(type(img))

array = img_to_array(img) 

print(type(array))
print(array.shape)

<class 'PIL.Image.Image'>
<class 'numpy.ndarray'>
(200, 200, 3)


### 複数のカラー画像データを読み込んで、4階テンソルの配列データに変換する

In [29]:
root_dir = '/content/gdrive/My Drive/Colab Notebooks/Python File Manipulation/'

files = os.listdir(os.path.join(root_dir,'test'))

print(files)

file=os.path.join(root_dir,'test/', files[0])

img = load_img(file,target_size=(200,200))

print(type(img))

array = img_to_array(img) 

print(type(array))



['SOB_B_TA-14-21978AB-400-012.png', 'SOB_B_TA-14-21978AB-400-013.png', 'SOB_B_TA-14-21978AB-400-014.png']
<class 'PIL.Image.Image'>
<class 'numpy.ndarray'>


In [37]:
temp_img_array_list = []

for img in files:
  
    file=os.path.join(root_dir,'test/', img)
    temp_img = load_img(file,target_size=(224,224))

    #PIL形式からNumpy配列に変換と正規化(224, 224, 3)
    temp_img_array = img_to_array(temp_img) /255

    #変換したNumpy配列を末尾に追加
    temp_img_array_list.append(temp_img_array)

print(temp_img_array)
print(type(temp_img_array))
print(len(temp_img_array_list))
print(type(temp_img_array_list[0]))
print(temp_img_array_list[0].shape)

[[[0.5803922  0.5411765  0.74509805]
  [0.6392157  0.5921569  0.7490196 ]
  [0.78039217 0.7254902  0.8235294 ]
  ...
  [0.9098039  0.9137255  0.89411765]
  [0.9098039  0.91764706 0.90588236]
  [0.92941177 0.9411765  0.9137255 ]]

 [[0.58431375 0.5372549  0.7176471 ]
  [0.63529414 0.5882353  0.7294118 ]
  [0.7529412  0.7019608  0.8039216 ]
  ...
  [0.8980392  0.90588236 0.8862745 ]
  [0.9098039  0.91764706 0.90588236]
  [0.92156863 0.93333334 0.8980392 ]]

 [[0.5764706  0.54901963 0.7137255 ]
  [0.62352943 0.5921569  0.74509805]
  [0.7137255  0.6784314  0.78431374]
  ...
  [0.8980392  0.90588236 0.8862745 ]
  [0.9098039  0.91764706 0.90588236]
  [0.9019608  0.9137255  0.8784314 ]]

 ...

 [[0.827451   0.827451   0.827451  ]
  [0.8509804  0.84313726 0.8627451 ]
  [0.8784314  0.87058824 0.8901961 ]
  ...
  [0.99215686 1.         0.9529412 ]
  [0.9372549  0.9490196  0.8745098 ]
  [0.8745098  0.88235295 0.827451  ]]

 [[0.9019608  0.8980392  0.88235295]
  [0.85882354 0.85882354 0.8666667 ]


In [42]:
import numpy as np


arr_1d = np.array(temp_img_array_list)

print(type(arr_1d))
print(arr_1d.shape)

<class 'numpy.ndarray'>
(3, 224, 224, 3)
